[versions]
annotations = "23.0.0"
lazydfu = "0.1.3"

# Minecraft
minecraft_version = "1.19.3"
minecraft_required = "1.19.3"
yarn = "1.19.3+build.2"
quilt_loader = "0.17.+"

# Plugins
loom = "1.+"
spotless = "5.+"
quiltflower = "1.+"
minotaur = "2.+"

[libraries]
# Minecraft & Fabric
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_version" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

# Libraries
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Mods
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }

[bundles]
compileOnly = ["annotations"]
mod_runtime = ["lazydfu"]

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
